version: '3'

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    image: mariadb
    networks:
      - my_network
    ports:
      - 3306
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
    env_file:
      - .env
    restart:
      always
  
  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    image: wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    ports:
      - "9000:9000"
    networks:
      - my_network
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    restart:
      always
  
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    image: nginx
    volumes:
      - wordpress_data:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - my_network
    env_file:
      - .env
    restart:
      always

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rlarabi/data/wordpress
  
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rlarabi/data/mariadb

networks:
  my_network:
    driver: bridge
